### PR TITLE
Profile page

### PR DESCRIPTION
**Pull request by frederikcreemers**
It's not done yet, but this way you can take a look, and give feedback if you want to.

### CODE REVIEW

**Comment by bshyong** [comment]
Sweet - can you post a link to this PR in the bounty? Thanks!

—

**Comment by barisser** [comment]
Hey nice start!  I guess you'll add a follow button and the number of posts?  There's a good conversation about this in the link below if you haven't seen it already.

https://assembly.com/textshots/bounties/22

**Comment by frederikcreemers** [comment]
I'll add a follow buton. It currently only shows up when you're logged in.
If you want it to show up even when you're not logged in, what should the
behavior be?

**Comment by barisser** [comment]
No that makes sense.  Can't follow unless you're logged in.  

On Medium, if you try to recommend something when you're not logged-in, it prompts you to sign up.  We could do this also.  Not super high priority though.

**Comment by bshyong** [comment]
Here's a screen showing how Medium pops a modal with a button to sign in with Twitter:

screen shot 2015-02-27 at 10 49 17 am

**Comment by frederikcreemers** [comment]
In my previous post, instead of "I'll add a follow button", I meant "I've already added..." Also, you don't see the button on your own profile. (see user_profile.jade).

I'll add the post count, and facebook/twitter/google metadata. Is there anything else that needs to be done within the scope of this bounty?

**Comment by barisser** [comment]
I think that's it.  Let me know when it's ready.  Thanks!

**Pull request merged**
