### PR TITLE
Add Fig and Dockerfile configs

### PR DESCRIPTION
**Pull request by shrikrishnaholla**
For easy local dev environment setup. 
@bshyong : bounty no [54](https://assembly.com/textshots/bounties/54)

### CODE REVIEW

**Comment by karan** [comment]
Can you update README to include more detailed instruction on how to install fig and docker on different OS's, what commands in all to run (`grunt`, `node app.js` etc)?

Thanks

**Comment by shrikrishnaholla** [comment]
@karan Added Fig and Docker installation instructions to README. No need to run `grunt` or `node` commands here. They will be taken care of by fig and docker :smile:

**Comment by karan** [comment]
@shrikrishnaholla 

I'm trying to get the env setup on my Macbook.

I installed boot2docker and fig, and made sure everything is setup. The `RUN npm install` command in Dockerfile is executed but no npm packages are installed.

Any potential fixes?

**Comment by karan** [comment]
https://github.com/asm-products/squall/commit/12e91212f9bd150a112a8b6523a9819db11e8a8c

EDIT: Can't say it's working 100% of the time.

**Comment by shrikrishnaholla** [comment]
Hey, that was my bad actually, the earlier version probably needed the addition of a line `mkdir -p /usr/src/app` before the `WORKDIR /usr/src/app` line.

**Pull request merged**
